name: DockerScout

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare
          image: index.docker.io/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}/scvanegasa-app:latest
          to: index.docker.io/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}/scvanegasa-app:latest
          ignore-unchanged: true
          only-severities: critical,high
          write-comment: true
          ignore-base: true

      - name: Analyze for critical and high CVEs
        id: docker-scout-cves
        uses: docker/scout-action@v1
        with:
          command: cves
          image: index.docker.io/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}/scvanegasa-app:latest
          sarif-file: sarif.output.json
          summary: true

      - name: Upload SARIF result
        id: upload-sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif.output.json
